services:
  - type: web
    name: chat-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chat-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENV
        value: production

databases:
  - name: chat-db
    databaseName: chatdb
    user: chatuser
